### ISSUE TITLE
Tested : 27C64

### ISSUE THREAD

**Issue by andremiller** [SukkoPera/Open2327RomAdapter#3]
Hi there,

I just wanted to give some feedback, as you mentioned on the main page that 27C64 should work, but has not been tested.

I've tested your adapter board, soldering bridges across all three resistor positions, and a 27C64 programmed with the standard 8K Kernal ROM (kernal.901227-03.bin) works perfectly as a replacement for the standard Kernal.

Further details:
- NMC27C64Q EPROM
- TL866II Programmer
- ROM: http://www.zimmers.net/anonftp/pub/cbm/firmware/computers/c64/kernal.901227-03.bin

Thanks for making this available!

**Comment by SukkoPera** [comment]
Thanks andre, I will update the table ASAP!
