### ISSUE TITLE
C64 Character Rom

### ISSUE THREAD

**Issue by timmit99** [SukkoPera/Open2327RomAdapter#4]
For a second version, would it be possible to have a jumper pad that is normally closed (connected) for address line 12? for the 4K character ROM's you can put 2 on a 28C64 and by toggling A12 can switch between the two.

If you have a cuttable trace jumper and on address line 12 and then a pin header/solder pad for the line it can ALSO be toggled to allow for more switching

**Comment by SukkoPera** [comment]
Like this?

![image](https://user-images.githubusercontent.com/1316870/79487515-a2f8b480-8018-11ea-8ed2-f7c21e87ea80.png)

**Comment by timmit99** [comment]
exactly! yeah, that would keep it connected for 99% of the applications, but if you wanted to use a 4K ROM image for character sets you can just cut that jumper and then toggle the A12 line

**Comment by SukkoPera** [comment]
Ok, I even managed to sneak in a pull-up resistor for A12.

![image](https://user-images.githubusercontent.com/1316870/79616980-abc7b400-8106-11ea-99e9-6768d088e21c.png)


Would you be willing to test this yourself, @timmit99? I mean get boards, etc.

**Comment by timmit99** [comment]
@SukkoPera yeah, if you send me gerbers i'll throw in an OSH park order and test them with my CharSetRoms!

**Comment by SukkoPera** [comment]
OK, send me an e-mail to mynick at gmail so that I have your address.

**Comment by SukkoPera** [comment]
OK, send me an e-mail to mynick at gmail so that I have your address.

**Comment by timmit99** [comment]
Could you just drop the gerber.zip here?

**Comment by SukkoPera** [comment]
Nope, I don't want them to be public.

**Comment by timmit99** [comment]
Email sent!

**Comment by timmit99** [comment]
Can you confirm you got it?

**Comment by SukkoPera** [comment]
I didn't! Maybe you didn't replace `mynick` with... my nick? :)

**Comment by timmit99** [comment]
resent!

**Comment by SukkoPera** [comment]
Sent :).

**Comment by timmit99** [comment]
Ordered through JLC with a few other projects, Will report back later.
Might fork this and change the layout a bit so A12 can be exposed on the edge as well.

**Comment by timmit99** [comment]
Works perfectly.
With an AT28C64 with two character ROM images on it. Cut the jumper pad (JP1) and put a 10K resistor on R4 with R1, R2, and R3 as 0 Ohm jumpers.

Connected a switch between the A12 pad and the ground pad and when switching it i can toggle between the two character sets.

**Comment by SukkoPera** [comment]
Thanks for testing and glad it works. I'm leaving this open so that I remember to release the new adapter and update the docs.

**Comment by timmit99** [comment]
If you need any information from me let me know! I can get some photos if you want.

**Comment by Obiwantje** [comment]
Any chance I can get my hands on this new Gerber please? Going to test on C64 CHAR ROM
